In [44]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [45]:
seed=7
np.random.seed(seed)

In [46]:
data=np.loadtxt('pima-indians-diabetes.csv',delimiter=',')
X=data[:,0:8]
y=data[:,8]

In [47]:
X

array([[   6.   ,  148.   ,   72.   , ...,   33.6  ,    0.627,   50.   ],
       [   1.   ,   85.   ,   66.   , ...,   26.6  ,    0.351,   31.   ],
       [   8.   ,  183.   ,   64.   , ...,   23.3  ,    0.672,   32.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,   26.2  ,    0.245,   30.   ],
       [   1.   ,  126.   ,   60.   , ...,   30.1  ,    0.349,   47.   ],
       [   1.   ,   93.   ,   70.   , ...,   30.4  ,    0.315,   23.   ]])

In [48]:
y

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [56]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [57]:
#Define and Compile
model=Sequential()
model.add(Dense(4,input_dim=8,kernel_initializer='uniform',activation='relu'))
model.add(Dense(4, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [59]:
#fit the model
model.fit(X_train,y_train,epochs=150,batch_size=10)

Epoch 1/150
576/576 [==============================] - 0s - loss: 0.4621 - acc: 0.7865     
Epoch 2/150
576/576 [==============================] - 0s - loss: 0.4616 - acc: 0.7899     
Epoch 3/150
576/576 [==============================] - 0s - loss: 0.4615 - acc: 0.7882     
Epoch 4/150
576/576 [==============================] - 0s - loss: 0.4614 - acc: 0.7899     
Epoch 5/150
576/576 [==============================] - 0s - loss: 0.4612 - acc: 0.7882     
Epoch 6/150
576/576 [==============================] - 0s - loss: 0.4611 - acc: 0.7899     
Epoch 7/150
576/576 [==============================] - 0s - loss: 0.4610 - acc: 0.7899     
Epoch 8/150
576/576 [==============================] - 0s - loss: 0.4612 - acc: 0.7899     
Epoch 9/150
576/576 [==============================] - 0s - loss: 0.4610 - acc: 0.7882     
Epoch 10/150
576/576 [==============================] - 0s - loss: 0.4605 - acc: 0.7899     
Epoch 11/150
576/576 [==============================] - 0s - loss: 0.4603 - acc

In [60]:
y_pred=model.predict(X_test)

In [61]:
y_pred=(y_pred>0.5)

In [63]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[110,  20],
       [ 23,  39]])

In [68]:
#evaluate the model
scores=model.evaluate(X_train,y_train)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

320/576 [===============>..............] - ETA: 0sacc: 78.99%


In [64]:
149+43

192

In [67]:
(149.0/192)*100

77.60416666666666