In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.


In [2]:
seed=7
np.random.seed(seed)

In [3]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
data=np.loadtxt('pima-indians-diabetes.csv',delimiter=',')
# data = np.genfromtxt('pima-indians-diabetes.csv',delimiter=',', dtype=None, names=col_names)
X=data[:,0:8]
y=data[:,8]

In [4]:
# read the data into a Pandas DataFrame
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
data = pd.read_csv(url, header=None, names=col_names)

In [5]:
feature_cols = ['pregnant', 'glucose', 'bp', 'insulin', 'bmi', 'age']
X=data[feature_cols].values
y=data.label.values

In [6]:
type(X)

numpy.ndarray

In [7]:
type(y)

numpy.ndarray

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [11]:
X_train

array([[ 1.50755225, -1.01521454, -0.40451932, -0.71823753, -1.22070104,
        -0.04863985],
       [-0.82986389, -0.09964691, -0.61509602,  0.08374747,  0.13719053,
        -0.88246592],
       [-1.12204091, -0.95207195,  0.54307587, -0.71823753,  0.0240329 ,
        -0.5489355 ],
       ..., 
       [ 0.04666716, -0.85735805, -0.24658679, -0.71823753, -0.9440935 ,
        -1.04923114],
       [ 2.09190629, -1.14149973,  0.2272108 , -0.71823753, -0.26514771,
         0.11812536],
       [ 0.33884418,  0.46863645,  0.64836422, -0.71823753, -4.04964181,
         2.953134  ]])

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
#Define and Compile
model=Sequential()
model.add(Dense(12,input_dim=6,kernel_initializer='uniform',activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
#fit the model
model.fit(X_train,y_train,epochs=200,batch_size=1)

Epoch 1/200
576/576 [==============================] - 11s - loss: 0.4259 - acc: 0.8194    
Epoch 2/200
576/576 [==============================] - 12s - loss: 0.4032 - acc: 0.8229    
Epoch 3/200
576/576 [==============================] - 11s - loss: 0.4070 - acc: 0.8177    
Epoch 4/200
576/576 [==============================] - 11s - loss: 0.3971 - acc: 0.8351    
Epoch 5/200
576/576 [==============================] - 11s - loss: 0.3932 - acc: 0.8281    
Epoch 6/200
576/576 [==============================] - 11s - loss: 0.3987 - acc: 0.8281    
Epoch 7/200
576/576 [==============================] - 11s - loss: 0.3925 - acc: 0.8299    
Epoch 8/200
576/576 [==============================] - 11s - loss: 0.3994 - acc: 0.8281    
Epoch 9/200
576/576 [==============================] - 10s - loss: 0.3935 - acc: 0.8229    
Epoch 10/200
576/576 [==============================] - 11s - loss: 0.3909 - acc: 0.8264    
Epoch 11/200
576/576 [==============================] - 11s - loss: 0.3936 - ac

In [26]:
y_pred=model.predict(X_test)

In [27]:
y_pred=(y_pred>0.5)

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[107  23]
 [ 25  37]]
0.75


In [29]:
#evaluate the model
scores=model.evaluate(X_train,y_train)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

576/576 [==============================] - 0s     
acc: 89.24%


In [38]:
151+41

192

In [39]:
(151.0/192)*100

78.64583333333334

In [30]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(12,input_dim=6,kernel_initializer='uniform',activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier


In [32]:
classifier=KerasClassifier(build_classifier,batch_size=1,epochs=150)
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=5,n_jobs=1)


Epoch 1/150
460/460 [==============================] - 9s - loss: 0.6861 - acc: 0.6239     
Epoch 2/150
460/460 [==============================] - 8s - loss: 0.6738 - acc: 0.6413     
Epoch 3/150
460/460 [==============================] - 8s - loss: 0.6661 - acc: 0.6413     
Epoch 4/150
460/460 [==============================] - 9s - loss: 0.6613 - acc: 0.6413     
Epoch 5/150
460/460 [==============================] - 9s - loss: 0.6584 - acc: 0.6413     
Epoch 6/150
460/460 [==============================] - 9s - loss: 0.6564 - acc: 0.6413     
Epoch 7/150
460/460 [==============================] - 9s - loss: 0.6551 - acc: 0.6413     
Epoch 8/150
460/460 [==============================] - 9s - loss: 0.6543 - acc: 0.6413     
Epoch 9/150
460/460 [==============================] - 9s - loss: 0.6537 - acc: 0.6413     
Epoch 10/150
460/460 [==============================] - 9s - loss: 0.6534 - acc: 0.6413     
Epoch 11/150
460/460 [==============================] - 9s - loss: 0.6532 - acc

In [33]:
mean=accuracies.mean()
print(mean)
variance=accuracies.std()
print(variance)
print(accuracies)

0.722353823088
0.0432582033841
[ 0.64655172  0.76521739  0.73913043  0.70434783  0.75652174]


In [57]:
#improving the ANN for overfitting sing dropout
from keras.layers import Dropout

classifier=Sequential()
classifier.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


classifier.fit(X_train,y_train,epochs=50,batch_size=5)

Epoch 1/50
576/576 [==============================] - 4s - loss: 0.6870 - acc: 0.6424     
Epoch 2/50
576/576 [==============================] - 4s - loss: 0.6282 - acc: 0.6424     
Epoch 3/50
576/576 [==============================] - 4s - loss: 0.5527 - acc: 0.6424     
Epoch 4/50
576/576 [==============================] - 4s - loss: 0.5302 - acc: 0.7153     
Epoch 5/50
576/576 [==============================] - 4s - loss: 0.5277 - acc: 0.7431     
Epoch 6/50
576/576 [==============================] - 4s - loss: 0.5257 - acc: 0.7535     
Epoch 7/50
576/576 [==============================] - 4s - loss: 0.5046 - acc: 0.7656     
Epoch 8/50
576/576 [==============================] - 4s - loss: 0.4996 - acc: 0.7743     
Epoch 9/50
576/576 [==============================] - 4s - loss: 0.5113 - acc: 0.7639     
Epoch 10/50
576/576 [==============================] - 4s - loss: 0.5190 - acc: 0.7639     
Epoch 11/50
576/576 [==============================] - 4s - loss: 0.5100 - acc: 0.7552   

In [ ]:
#tuning takes lot of time run in spyder or other IDE

In [37]:
#Tuning the ANN
from sklearn.model_selection import GridSearchCV

def build_classifier(optimizer):
    classifier=Sequential()
    classifier.add(Dense(12,input_dim=6,kernel_initializer='uniform',activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier
classifier=KerasClassifier(build_fn=build_classifier)
parameters={'batch_size':[40,50],
           'epochs':[10,15],
           'optimizer':['adam','rmsprop']}
grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10)
grid_search=grid_search.fit(X_train,y_train)
best_parameters=grid_search.best_params_
best_Accuracy=grid_search.best_score_
print(best_parameters,best_Accuracy)

Epoch 1/10
518/518 [==============================] - 0s - loss: 0.6923 - acc: 0.6409     
Epoch 2/10
518/518 [==============================] - 0s - loss: 0.6905 - acc: 0.6409     
Epoch 3/10
518/518 [==============================] - 0s - loss: 0.6883 - acc: 0.6409     
Epoch 4/10
518/518 [==============================] - 0s - loss: 0.6857 - acc: 0.6409     
Epoch 5/10
518/518 [==============================] - 0s - loss: 0.6819 - acc: 0.6409     
Epoch 6/10
518/518 [==============================] - 0s - loss: 0.6760 - acc: 0.6409     
Epoch 7/10
518/518 [==============================] - 0s - loss: 0.6652 - acc: 0.6409     
Epoch 8/10
518/518 [==============================] - 0s - loss: 0.6474 - acc: 0.6409     
Epoch 9/10
518/518 [==============================] - 0s - loss: 0.6201 - acc: 0.6409     
Epoch 10/10
518/518 [==============================] - 0s     
Epoch 1/10
518/518 [==============================] - 0s - loss: 0.6925 - acc: 0.6429     
Epoch 2/10
518/518 [=======

In [34]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit(X_train,y_train)
y1=model.predict(X_test)
y1=(y1>0.5)

from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y1))
print(accuracy_score(y_test,y1))

[[118  12]
 [ 26  36]]
0.802083333333


In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y1)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y1)

0.80208333333333337

In [60]:
from sklearn.svm import SVC
model=SVC(kernel='poly')
model.fit(X_train,y_train)
y_svc=model.predict(X_test)
y_svc=(y_svc>0.5)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_svc)

array([[125,   5],
       [ 43,  19]])

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_svc)

0.75

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores=cross_val_score(model,X,y,scoring='accuracy',cv=10)
# print(scores)
# print(scores.mean())

In [ ]:
from sklearn import model_selection,linear_model,preprocessing,svm,tree,neighbors,ensemble,metrics,naive_bayes

In [13]:
def class_model(model):
    model.fit(X_train,y_train)
    ytrain_pred=model.predict(X_train)
    ytest_pred=model.predict(X_test)
    accuracy_train=metrics.accuracy_score(y_train,ytrain_pred)
    accuracy_test=metrics.accuracy_score(y_test,ytest_pred)
    train_error=metrics.mean_absolute_error(y_train,ytrain_pred)
    test_error=metrics.mean_absolute_error(y_test,ytest_pred)
    print('Accuracy_train=%s' % '{0:.3%}'.format(accuracy_train),'train error=%s' % '{0:.3%}'.format(train_error))
    print('Accuracy_test=%s' % '{0:.3%}'.format(accuracy_test),'test error=%s' % '{0:.3%}'.format(test_error))

In [285]:
model=linear_model.LogisticRegression()
class_model(model)
scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
print(scores.mean())

('Accuracy_train=76.562%', 'train error=23.438%')
('Accuracy_test=80.208%', 'test error=19.792%')
0.766968557758


In [14]:
model=linear_model.SGDClassifier()
class_model(model)

('Accuracy_train=56.250%', 'train error=43.750%')
('Accuracy_test=62.500%', 'test error=37.500%')


In [16]:
model=svm.SVC(kernel='rbf')
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=73.264%', 'train error=26.736%')
('Accuracy_test=67.708%', 'test error=32.292%')


In [20]:
model=ensemble.RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=10)
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=97.049%', 'train error=2.951%')
('Accuracy_test=71.354%', 'test error=28.646%')


In [22]:
model=naive_bayes.GaussianNB()
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=67.535%', 'train error=32.465%')
('Accuracy_test=68.750%', 'test error=31.250%')


In [23]:
#k fold cross validation
model=neighbors.KNeighborsClassifier(n_neighbors=5)
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=77.083%', 'train error=22.917%')
('Accuracy_test=70.312%', 'test error=29.688%')


In [ ]:
from sklearn.grid_search import GridSearchCV

In [ ]:
k_range=range(1,51)
print(k_range)
weight_options=['uniform','distance']
param_grid=dict(n_neighbors=k_range,weights=weight_options)
print(param_grid)
grid=GridSearchCV(model,param_grid,cv=10,scoring='accuracy')


In [ ]:
grid.fit(X,y)

In [ ]:
grid.grid_scores_

In [ ]:
print grid.grid_scores_[0].parameters
print grid.grid_scores_[0].cv_validation_scores
print grid.grid_scores_[0].mean_validation_score

In [ ]:
print grid.best_estimator_
print grid.best_params_
print grid.best_score_

In [ ]:
from sklearn.grid_search import RandomizedSearchCV
param_dist=dict(n_neighbors=k_range,weights=weight_options)
rand=RandomizedSearchCV(model,param_dist,cv=10,scoring='accuracy',n_iter=10,random_state=5)
rand.fit(X,y)
rand.grid_scores_

In [ ]:
print rand.best_params_
print rand.best_score_

In [39]:
!pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.1-cp35-cp35m-win_amd64.whl

tensorflow-1.2.1-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
