In [25]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.


In [26]:
seed=7
np.random.seed(seed)

In [76]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
data=np.loadtxt('pima-indians-diabetes.csv',delimiter=',')
# data = np.genfromtxt('pima-indians-diabetes.csv',delimiter=',', dtype=None, names=col_names)
X=data[:,0:8]
y=data[:,8]

In [27]:
# read the data into a Pandas DataFrame
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
data = pd.read_csv(url, header=None, names=col_names)

In [40]:
feature_cols = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age']
X=data[feature_cols].values
y=data.label.values

In [109]:
type(X)

numpy.ndarray

In [110]:
type(y)

numpy.ndarray

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [42]:
X_train

array([[   9.   ,   89.   ,   62.   , ...,   22.5  ,    0.142,   33.   ],
       [   1.   ,  118.   ,   58.   , ...,   33.3  ,    0.261,   23.   ],
       [   0.   ,   91.   ,   80.   , ...,   32.4  ,    0.601,   27.   ],
       ..., 
       [   4.   ,   94.   ,   65.   , ...,   24.7  ,    0.148,   21.   ],
       [  11.   ,   85.   ,   74.   , ...,   30.1  ,    0.3  ,   35.   ],
       [   5.   ,  136.   ,   82.   , ...,    0.   ,    0.64 ,   69.   ]])

In [43]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [44]:
#Define and Compile
model=Sequential()
model.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [45]:
#fit the model
model.fit(X_train,y_train,epochs=100,batch_size=5)

Epoch 1/100
576/576 [==============================] - 2s - loss: 0.6849 - acc: 0.6424     
Epoch 2/100
576/576 [==============================] - 2s - loss: 0.5819 - acc: 0.6424     
Epoch 3/100
576/576 [==============================] - 2s - loss: 0.5294 - acc: 0.6424     
Epoch 4/100
576/576 [==============================] - 2s - loss: 0.5204 - acc: 0.6823     
Epoch 5/100
576/576 [==============================] - 2s - loss: 0.5160 - acc: 0.7691     
Epoch 6/100
576/576 [==============================] - 2s - loss: 0.5120 - acc: 0.7743     
Epoch 7/100
576/576 [==============================] - 2s - loss: 0.5087 - acc: 0.7604     
Epoch 8/100
576/576 [==============================] - 2s - loss: 0.5060 - acc: 0.7691     
Epoch 9/100
576/576 [==============================] - 2s - loss: 0.5028 - acc: 0.7743     
Epoch 10/100
576/576 [==============================] - 2s - loss: 0.4995 - acc: 0.7830     
Epoch 11/100
576/576 [==============================] - 2s - loss: 0.4964 - acc

In [46]:
y_pred=model.predict(X_test)

In [47]:
y_pred=(y_pred>0.5)

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[114  16]
 [ 24  38]]
0.791666666667


In [49]:
#evaluate the model
scores=model.evaluate(X_train,y_train)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

480/576 [========================>.....] - ETA: 0sacc: 84.72%


In [38]:
151+41

192

In [39]:
(151.0/192)*100

78.64583333333334

In [53]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier


In [54]:
classifier=KerasClassifier(build_classifier,batch_size=5,epochs=50)
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=5,n_jobs=1)


Epoch 1/50
460/460 [==============================] - 2s - loss: 0.6885 - acc: 0.6391     
Epoch 2/50
460/460 [==============================] - 2s - loss: 0.6356 - acc: 0.6413     
Epoch 3/50
460/460 [==============================] - 2s - loss: 0.5353 - acc: 0.6413     
Epoch 4/50
460/460 [==============================] - 2s - loss: 0.5204 - acc: 0.7130     
Epoch 5/50
460/460 [==============================] - 2s - loss: 0.5101 - acc: 0.7696     
Epoch 6/50
460/460 [==============================] - 2s - loss: 0.5014 - acc: 0.7478     
Epoch 7/50
460/460 [==============================] - 2s - loss: 0.4920 - acc: 0.7522     
Epoch 8/50
460/460 [==============================] - 2s - loss: 0.4862 - acc: 0.7630     
Epoch 9/50
460/460 [==============================] - 2s - loss: 0.4804 - acc: 0.7609     
Epoch 10/50
460/460 [==============================] - 2s - loss: 0.4756 - acc: 0.7696     
Epoch 11/50
460/460 [==============================] - 2s - loss: 0.4735 - acc: 0.7696   

In [55]:
mean=accuracies.mean()
print(mean)
variance=accuracies.std()
print(variance)
print(accuracies)

0.753418301566
0.0193280982965
[ 0.78448277  0.7478261   0.73913045  0.73043479  0.7652174 ]


In [57]:
#improving the ANN for overfitting sing dropout
from keras.layers import Dropout

classifier=Sequential()
classifier.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


classifier.fit(X_train,y_train,epochs=50,batch_size=5)

Epoch 1/50
576/576 [==============================] - 4s - loss: 0.6870 - acc: 0.6424     
Epoch 2/50
576/576 [==============================] - 4s - loss: 0.6282 - acc: 0.6424     
Epoch 3/50
576/576 [==============================] - 4s - loss: 0.5527 - acc: 0.6424     
Epoch 4/50
576/576 [==============================] - 4s - loss: 0.5302 - acc: 0.7153     
Epoch 5/50
576/576 [==============================] - 4s - loss: 0.5277 - acc: 0.7431     
Epoch 6/50
576/576 [==============================] - 4s - loss: 0.5257 - acc: 0.7535     
Epoch 7/50
576/576 [==============================] - 4s - loss: 0.5046 - acc: 0.7656     
Epoch 8/50
576/576 [==============================] - 4s - loss: 0.4996 - acc: 0.7743     
Epoch 9/50
576/576 [==============================] - 4s - loss: 0.5113 - acc: 0.7639     
Epoch 10/50
576/576 [==============================] - 4s - loss: 0.5190 - acc: 0.7639     
Epoch 11/50
576/576 [==============================] - 4s - loss: 0.5100 - acc: 0.7552   

In [ ]:
#tuning takes lot of time run in spyder or other IDE

In [ ]:
#Tuning the ANN
from sklearn.model_selection import GridSearchCV

def build_classifier(optimizer):
     classifier=Sequential()
    classifier.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier
classifier=KerasClassifier(build_fn=build_classifier)
parameters={'batch_size':[20,30],
           'epochs':[100,150],
           'optimizer':['adam','rmsprop']}
grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10)
grid_search=grid_search.fit(X_train,y_train)
best_parameters=grid_search.best_params_
best_Accuracy=grid_search.best_score_
print(best_parameters,best_Accuracy)

Epoch 1/50
518/518 [==============================] - 0s - loss: 0.6919 - acc: 0.6313     
Epoch 2/50
518/518 [==============================] - 0s - loss: 0.6889 - acc: 0.6409     
Epoch 3/50
518/518 [==============================] - 0s - loss: 0.6848 - acc: 0.6409     
Epoch 4/50
518/518 [==============================] - 0s - loss: 0.6784 - acc: 0.6409     
Epoch 5/50
518/518 [==============================] - 0s - loss: 0.6687 - acc: 0.6409     
Epoch 6/50
518/518 [==============================] - 0s - loss: 0.6555 - acc: 0.6409     
Epoch 7/50
518/518 [==============================] - 0s - loss: 0.6383 - acc: 0.6409     
Epoch 8/50
518/518 [==============================] - 0s - loss: 0.6186 - acc: 0.6409     
Epoch 9/50
518/518 [==============================] - 0s - loss: 0.5994 - acc: 0.6409     
Epoch 10/50
518/518 [==============================] - 0s - loss: 0.5825 - acc: 0.6409     
Epoch 11/50
518/518 [==============================] - 0s - loss: 0.5684 - acc: 0.6409   

In [58]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit(X_train,y_train)
y1=model.predict(X_test)
y1=(y1>0.5)

from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y1))
print(accuracy_score(y_test,y1))

[[118  12]
 [ 26  36]]
0.802083333333


In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y1)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y1)

0.80208333333333337

In [60]:
from sklearn.svm import SVC
model=SVC(kernel='poly')
model.fit(X_train,y_train)
y_svc=model.predict(X_test)
y_svc=(y_svc>0.5)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_svc)

array([[125,   5],
       [ 43,  19]])

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_svc)

0.75

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores=cross_val_score(model,X,y,scoring='accuracy',cv=10)
# print(scores)
# print(scores.mean())

In [ ]:
from sklearn import model_selection,linear_model,preprocessing,svm,tree,neighbors,ensemble,metrics,naive_bayes

In [13]:
def class_model(model):
    model.fit(X_train,y_train)
    ytrain_pred=model.predict(X_train)
    ytest_pred=model.predict(X_test)
    accuracy_train=metrics.accuracy_score(y_train,ytrain_pred)
    accuracy_test=metrics.accuracy_score(y_test,ytest_pred)
    train_error=metrics.mean_absolute_error(y_train,ytrain_pred)
    test_error=metrics.mean_absolute_error(y_test,ytest_pred)
    print('Accuracy_train=%s' % '{0:.3%}'.format(accuracy_train),'train error=%s' % '{0:.3%}'.format(train_error))
    print('Accuracy_test=%s' % '{0:.3%}'.format(accuracy_test),'test error=%s' % '{0:.3%}'.format(test_error))

In [285]:
model=linear_model.LogisticRegression()
class_model(model)
scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
print(scores.mean())

('Accuracy_train=76.562%', 'train error=23.438%')
('Accuracy_test=80.208%', 'test error=19.792%')
0.766968557758


In [14]:
model=linear_model.SGDClassifier()
class_model(model)

('Accuracy_train=56.250%', 'train error=43.750%')
('Accuracy_test=62.500%', 'test error=37.500%')


In [16]:
model=svm.SVC(kernel='rbf')
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=73.264%', 'train error=26.736%')
('Accuracy_test=67.708%', 'test error=32.292%')


In [20]:
model=ensemble.RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=10)
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=97.049%', 'train error=2.951%')
('Accuracy_test=71.354%', 'test error=28.646%')


In [22]:
model=naive_bayes.GaussianNB()
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=67.535%', 'train error=32.465%')
('Accuracy_test=68.750%', 'test error=31.250%')


In [23]:
#k fold cross validation
model=neighbors.KNeighborsClassifier(n_neighbors=5)
class_model(model)
# scores=cross_val_score(model,X,y,cv=10,scoring='accuracy')
# print(scores.mean())

('Accuracy_train=77.083%', 'train error=22.917%')
('Accuracy_test=70.312%', 'test error=29.688%')


In [ ]:
from sklearn.grid_search import GridSearchCV

In [ ]:
k_range=range(1,51)
print(k_range)
weight_options=['uniform','distance']
param_grid=dict(n_neighbors=k_range,weights=weight_options)
print(param_grid)
grid=GridSearchCV(model,param_grid,cv=10,scoring='accuracy')


In [ ]:
grid.fit(X,y)

In [ ]:
grid.grid_scores_

In [ ]:
print grid.grid_scores_[0].parameters
print grid.grid_scores_[0].cv_validation_scores
print grid.grid_scores_[0].mean_validation_score

In [ ]:
print grid.best_estimator_
print grid.best_params_
print grid.best_score_

In [ ]:
from sklearn.grid_search import RandomizedSearchCV
param_dist=dict(n_neighbors=k_range,weights=weight_options)
rand=RandomizedSearchCV(model,param_dist,cv=10,scoring='accuracy',n_iter=10,random_state=5)
rand.fit(X,y)
rand.grid_scores_

In [ ]:
print rand.best_params_
print rand.best_score_